version: "3"
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./s3:/var/www/images
      - ./deals-client/dist:/var/www/client
    ports:
      - 80:80

  # ws:
  #   restart: always
  #   build: ./ws
  #   ports:
  #     - 3000:3000

  # bg-tasks:
  #   image: node:10.16-alpine
  #   working_dir: /home/node/app
  #   volumes:
  #     - ./bg-processes:/home/node/app
  #   environment:
  #     NODE_ENV: development
  #   command: npm run start-nc

  # deals-client:
  #   image: node:10.16-alpine
  #   working_dir: /home/node/app
  #   volumes:
  #     - ./deals-client:/home/node/app
  #   environment:
  #     NODE_ENV: development
  #   command: npm run serve
  #   ports:
  #     - 8080:8080

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/sql_scripts:/docker-entrypoint-initdb.d/
      - ./db/config:/etc/mysql/conf.d
    ports:
      - 3306:3306

  minio:
    image: minio/minio:latest
    volumes:
      - ./s3:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
