version: '3'
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/game_schema.sql:/docker-entrypoint-initdb.d/game_schema.sql
    ports:
      - "3306:3306"